[package]
name = "windchime"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }

# For demultiplexing:
bio = "2.0.3"
flate2 = "1.0"
indicatif = "0.17.11"
rayon = "1.6"
csv = "1.3.1"
reqwest = { version = "0.12.12" , features = ["blocking"]}